language: java

after_success:
  - mvn clean test jacoco:report coveralls:report

deploy:
  provider: script
  script: 
  - echo $SIGNING_KEY | base64 --decode > signingkey.asc
  - gpg --fast-import signingkey.asc
  - cp .travis.settings.xml $HOME/.m2/settings.xml
  - mvn clean deploy -P release
  on:
    tags: true