language: java

after_success:
  - mvn clean test jacoco:report coveralls:report
  - gpg --version
  - gpg2 --version
  - ./deploy/deploy.sh

deploy:
  provider: script
  script: ./deploy/deploy.sh
  on:
    all_branches: true