language: java

after_success:
  - mvn clean test jacoco:report coveralls:report

before_deploy:
  - "mvn -DskipTests package -P release"
  - export FILE_NAMES=$(ls target/jcomplex-*.jar)

deploy:
  - provider: script
    script: deploy/deploy.sh
    on:
      tags: true 
  - provider: releases
    file: "${FILE_NAMES}"
    on:
      tags: true 